name: CI/CD Pipeline

on:
  push:
    branches:
      - test-ci-cd  # Change to `main` when ready for production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: SSH into EC2 instance and deploy
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}            # EC2 public IP
          username: ${{ secrets.EC2_USER }}        # SSH username, e.g., `ubuntu`
          key: ${{ secrets.EC2_SSH_KEY }}          # Private SSH key for EC2
          script: |
            # Navigate to the application directory
            cd ~/redd_chatbot_new

            # Pull the latest code from the test-ci-cd branch
            git pull origin test-ci-cd
            
            # Build the Docker image
            docker build -t streamlit-app .

            # Stop and remove any existing container with the same name
            docker stop streamlit-app || true
            docker rm streamlit-app || true

            # Run the Docker container with environment variables and restart policy
            docker run -d -p 8501:8501 \
              --name streamlit-app \
              --env-file .env \                      # Loads environment variables
              --restart unless-stopped \             # Restarts container automatically on failure or reboot
              streamlit-app